### ISSUE TITLE
Esp8266 Porting

### ISSUE THREAD

**Issue by zyon2k** [etimou/SomfyRTS#1]
Hello,
are you planning an Esp8266 porting of this library?

**Comment by etimou** [comment]
hi, thank you for your message. It was started but never tested. If you are interested, please check the esp8266 branch in the repo.
I've just uploaded it.

**Comment by zyon2k** [comment]
Hi, I've tried and it works...
Thank you for your work and for the responsiveness

**Comment by etimou** [comment]
thank you for your feedback. I've merged the esp8266 with the master branch
