### ISSUE TITLE
Improve latency (use fast writes)

### ISSUE THREAD

**Issue by mike-k68** [etimou/SomfyRTS#3]
Since we are dealing with microseconds, it is better to set the output HIGH or LOW directly with register handling, rather than using digitalWrite:

instead of 
digitalWrite(_pinTx, HIGH);
use for Arduino: **PORTD |= 1<<_pinTx;**
or use for ESP8266: **GPOS = 1<<_pinTx;**

instead of
digitalWrite(_pinTx, LOW);
use for Arduino: **PORTD &= !(1<<_pinTx);**
or use for ESP8266: **GPOC = 1<<_pinTx;**

**Comment by mike-k68** [comment]
fix included in pull request

**Comment by etimou** [comment]
fixed
