### ISSUE TITLE
Disable interrupts when transmitting

### ISSUE THREAD

**Issue by mike-k68** [etimou/SomfyRTS#5]
Since we are dealing with microseconds, we don't want to be disturbed by interrupts.

I suggest:

void SomfyRTS::sendSomfy(unsigned char virtualRemoteNumber, unsigned char actionCommand) {
  _virtualRemoteNumber = virtualRemoteNumber;
  _actionCommand = actionCommand;

  buildFrameSomfy();
  **noInterrupts();**
  sendCommandSomfy(2);
  for (int i = 0; i < 2; i++) {
    sendCommandSomfy(7);
  }
  **interrupts();**
}

**Comment by mike-k68** [comment]
fix included in pull request

**Comment by etimou** [comment]
fixed
