### ISSUE TITLE
Error retrieving Rolling Code in EEPROM

### ISSUE THREAD

**Issue by mike-k68** [etimou/SomfyRTS#6]
With ESP8266 "unsigned int" has 32-bit size, so when performing:
**EEPROM.get(_EEPROM_address + 2 * _virtualRemoteNumber, Code);**
we read 32 bits (4 bytes) and we get the Rolling Code of 2 remotes;
Code must be 16 bits (2 bytes) long so that EEPROM.get and EEPROM.put handle it correctly:
either "uint16_t" or "unsigned short"
We need to change this line :
  **unsigned int Code;**
to:
  **uint16_t Code;**

Same thing when performing:
**EEPROM.put(_EEPROM_address + 2 * _virtualRemoteNumber, Code + 1);**
Even after changing Code to uint16_t, when "putting" the new rollcode:
"Code" is uint16_t and "1" is int, so "Code + 1" is int (4 bytes), so when writing one remote, the next remote is overwritten.
We need to change this line to:
**EEPROM.put(_EEPROM_address + 2 * _virtualRemoteNumber, (uint16_t) (Code + 1));**
or simply:
**EEPROM.put(_EEPROM_address + 2 * _virtualRemoteNumber, ++Code);**

**Comment by mike-k68** [comment]
fix included in pull request

**Comment by etimou** [comment]
fixed
